### ISSUE TITLE
How do I activate workspace name badge on eclipse icon

### ISSUE THREAD

**Issue by Aditya-dixit** [turesheim/eclipse-launcher#5287]
The name badge comes up when I just start the eclipse but goes away then.
How do I activate it for dock eclipse icon and task switcher icon both?
I have set the workspace name in Preferences->General->Workspace

**Comment by FoxyBOA** [comment]
Any hint on how to fix that behavior (i.e., disappearing the badge after a specific time after opening a workspace - usually a few seconds)?
