### ISSUE TITLE
Badge color and size

### ISSUE THREAD

**Issue by asmittal** [turesheim/eclipse-launcher#5288]
First of all thanks, this works beautifully. The badge really helps in finding the correct eclipse you want to move to. 
But the color (red) and location of badge is very similar to when mac wants to notify you about new activity on an app. Say a new mail in outlook or new message on slack. 
Because of this, every time you are shifting to different app, and application switcher shows all icons, it gives a feel that there is new notification on some app. 
Can you please change the color and size to differentiate the eclipse badge.
Regards.

**Comment by turesheim** [comment]
I have been looking in to this, and there is no straightforward way of doing what you want. What you describe is exactly what is happening, the Eclipse launcher is somewhat abusing the badge mechanism. https://developer.apple.com/design/human-interface-guidelines/macos/system-capabilities/notifications/
