### ISSUE TITLE
Badge not working unless it is installed first

### ISSUE THREAD

**Issue by venukbh** [turesheim/eclipse-launcher#5289]
I recently downloaded eclipse oxygen 3.a and just opened an empty workspace and installed the plugin and it works fine further. 

But if I install any other plugin or update the eclipse.ini file for a shared plugins location, and then install this plugin as a 2nd plugin, I do not see the plugin working, I do not see "Open workspace" option.

**Comment by turesheim** [comment]
Closing as no new information was provided.
