### ISSUE TITLE
Unable to read repository error

### ISSUE THREAD

**Issue by kdorking** [turesheim/eclipse-launcher#5298]
I get the following error when trying to download via the Marketplace:

Unable to read repository at https://resheim.net/p2/eclipse-launcher/content.xml.
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Any indication as to what may be causing the repository to be unreadable?

Thanks

**Comment by turesheim** [comment]
Yes, my SSL certificate expired recently and I replaced it with a Let's Encrypt certificate. This should work now,  if your Java version is higher than [Java 8u101](https://bugs.openjdk.java.net/browse/JDK-8154757).

**Comment by kdorking** [comment]
I am running Java 8u231 and it does not work.

**Comment by turesheim** [comment]
So, I just tested with Java 8u144 and did not have any issues. Please make sure that the `-vm` argument in `eclipse.ini` points to the correct Java version. For example `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre/lib/server/libjvm.dylib`.

**Comment by kdorking** [comment]
Thanks, it was a java version problem, installed fine now.
