### ISSUE TITLE
Add support for Apple M1 ?

### ISSUE THREAD

**Issue by tomzeller** [turesheim/eclipse-launcher#5306]
Appreciate your work, thank you.

I am unable to install on Apple M1 using Eclipse 4.20M3 for Arm64/AArch64 :

```
Cannot complete the install because some dependencies are not satisfiable
  org.eclipse.equinox.p2.iu; net.resheim.eclipse.launcher.feature.group [3.0.2.202004261020,3.0.2.202004261020] cannot be installed in this environment because its filter is not applicable.
```

Maybe the x86_64 feature filter needs to be removed ? Just guessing.

Thanks again.

**Comment by guw** [comment]
@turesheim Any chance to get that support added?
